version: '3.7'

services:
   db:
     image: mysql:8.0
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_ROOT_PASSWORD: rootpassword
       MYSQL_DATABASE: teledoc
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword     
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   teledocapp:
     depends_on:
       - db
     image: 06262016/teledoc:runtime
     build:
       context: .
     ports:
       - "80:5000"

volumes:
    dbdata: